AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API Service for News Audio Application

Globals:
  Function:
    Timeout: 10
    MemorySize: 128
    Runtime: python3.10
    Architectures:
      - x86_64

Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Deployment stage (environment)
  
  S3BucketName:
    Type: String
    Default: news-audio-files-kenchang198-dev
    Description: S3 bucket for audio files and metadata

# ------------------------------------------------------------
# Resources
# ------------------------------------------------------------

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      EndpointConfiguration: REGIONAL
      BinaryMediaTypes:
        - 'audio/mpeg'
        - 'audio/wav'
        - 'audio/*'
        - '*/*'

  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: lambda_function.lambda_handler
      Description: API handler for News Audio Application
      Environment:
        Variables:
          S3_BUCKET: !Ref S3BucketName
          S3_PREFIX: audio/
          S3_METADATA_PREFIX: data/metadata/
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:ListBucket
              Resource:
                - !Sub "arn:aws:s3:::${S3BucketName}"
                - !Sub "arn:aws:s3:::${S3BucketName}/*"
      Events:
        ProxyApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /{proxy+}
            Method: ANY

Outputs:
  ApiFunction:
    Description: "API Lambda Function ARN"
    Value: !GetAtt ApiFunction.Arn
  
  ApiURL:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/"
  
  S3BucketName:
    Description: "S3 bucket for audio files"
    Value: !Ref S3BucketName
